from __future__ import annotations

import pytest

from orca_agent.evidence.p6_observations import (
    _decode,
    _number,
    _parse_frequency_section,
    _parse_normal_modes,
    _parse_scalar_section,
    _parse_stdout_frequencies,
    _parse_thermochemistry,
    parse_hessian_observations,
    parse_stdout_observations,
)


def _hessian(
    *,
    modes: str = "0 1 2\n0 1.0 0.0 0.0\n1 0.0 1.0 0.0\n2 0.0 0.0 1.0",
    frequencies: str = "3\n0 0.00\n1 -1.25D+00\n2 2.0",
    scale: str = "0.98",
) -> bytes:
    return (
        "$normal_modes\n3 3\n"
        + modes
        + "\n$vibrational_frequencies\n"
        + frequencies
        + "\n$frequency_scale_factor\n"
        + scale
        + "\n"
    ).encode()


def test_hessian_and_stdout_observations_preserve_tokens_spans_and_context() -> None:
    hessian = parse_hessian_observations(_hessian())
    assert hessian.hessian_dimension == 3
    assert hessian.frequency_tokens == ("0.00", "-1.25D+00", "2.0")
    assert hessian.frequencies == (0.0, -1.25, 2.0)
    assert hessian.normal_modes == ((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0))
    assert hessian.scale_factor == pytest.approx(0.98)
    stdout = b"""VIBRATIONAL FREQUENCIES
Scaling factor for frequencies = 0.980000000 (already applied!)
0: 0.00 cm**-1
1: -1.25D+00 cm**-1
2: 2.0 cm**-1
THERMOCHEMISTRY AT 298.15K
Temperature ... 298.15 K
Pressure ... 1.00 atm
Quasi RRHO ... True
Cut-Off Frequency ... 1.00 cm^-1
QRRHO uses reference frequency of 100.0 cm-1
Point Group: C2v, Symmetry Number: 2
"""
    combined = parse_stdout_observations(stdout, hessian)
    assert combined.stdout_frequency_tokens == ("0.00", "-1.25D+00", "2.0")
    assert combined.stdout_scale_factor == pytest.approx(0.98)
    assert combined.thermochemistry.temperature_K == pytest.approx(298.15)
    assert combined.thermochemistry.pressure_atm == pytest.approx(1.0)
    assert combined.thermochemistry.quasi_rrho is True
    assert combined.thermochemistry.qrrho_reference_frequency_cm1 == pytest.approx(100.0)
    assert combined.thermochemistry.symmetry_number == 2
    assert set(combined.thermochemistry.spans) == {
        "temperature_K",
        "pressure_atm",
        "quasi_rrho",
        "cutoff_frequency_cm1",
        "qrrho_reference_frequency_cm1",
        "symmetry_number",
    }


def test_stdout_without_frequency_marker_uses_empty_observation_defaults() -> None:
    parsed = parse_stdout_observations(b"ordinary ORCA output without a frequency block")
    assert parsed.hessian_dimension == 0
    assert parsed.stdout_frequency_tokens == ()
    assert parsed.stdout_scale_factor is None
    assert parsed.thermochemistry.missing_reasons == ("thermochemistry_block_not_unique",)


@pytest.mark.parametrize(
    "value",
    [b"", bytes([0xFF]), b"$normal_modes\n1 1\n0\n$vibrational_frequencies\n1\n0 0\n"],
)
def test_observation_decoding_and_required_sections_fail_closed(value: bytes) -> None:
    if value == b"$normal_modes\n1 1\n0\n$vibrational_frequencies\n1\n0 0\n":
        with pytest.raises(ValueError, match="normal_modes matrix is incomplete"):
            parse_hessian_observations(value)
    else:
        with pytest.raises(ValueError):
            parse_hessian_observations(value)
    if value in (b"", bytes([0xFF])):
        with pytest.raises(ValueError):
            _decode(value, "test")
    else:
        assert _decode(value, "test").startswith("$normal_modes")


def test_hessian_section_and_frequency_structure_reject_malformed_input() -> None:
    with pytest.raises(ValueError, match="missing normal_modes"):
        parse_hessian_observations(b"$vibrational_frequencies\n1\n0 0\n")
    with pytest.raises(ValueError, match="duplicate Hessian"):
        parse_hessian_observations(_hessian() + b"$normal_modes\n3 3\n")
    cases = (
        "",
        "not-a-dimension\n0 0\n1 1\n2 2",
        "100001\n0 0",
        "3\nnot-a-row",
        "3\n0 0\n0 1\n2 2",
        "3\n0 0\n2 2",
    )
    for body in cases:
        with pytest.raises(ValueError):
            _parse_frequency_section("", body, 0)


@pytest.mark.parametrize(
    "body",
    [
        "",
        "2 3\n0 1\n0 1.0",
        "2 2\n0 0\n0 1 2",
        "2 2\n0 1\n0 1.0 2.0\n0 3.0 4.0",
        "2 2\n0 1\n2 1.0 2.0",
        "2 2\n0 1\n0 1.0 2.0",
        "2 2\n0 1\n0 1.0 2.0\n1 3.0",
    ],
)
def test_normal_mode_matrix_rejects_empty_invalid_duplicate_or_incomplete_rows(body: str) -> None:
    with pytest.raises(ValueError):
        _parse_normal_modes(body, 2)


def test_normal_mode_matrix_accepts_comment_lines_and_scalar_sections_are_bounded() -> None:
    matrix = _parse_normal_modes("# generated by test\n2 2\n0 1\n0 1.0 0.0\n1 0.0 1.0", 2)
    assert matrix == ((1.0, 0.0), (0.0, 1.0))
    assert _parse_scalar_section("", None, "scale") == (None, None)
    with pytest.raises(ValueError, match="scale is invalid"):
        _parse_scalar_section("", ("no number", 0, 9), "scale")
    assert _parse_scalar_section("", ("value=1.2D+1", 0, 12), "scale")[0] == 12.0


def test_stdout_frequency_parser_handles_missing_scale_and_rejects_duplicate_or_gaps() -> None:
    assert _parse_stdout_frequencies("no marker") == ((), (), None)
    assert _parse_stdout_frequencies("VIBRATIONAL FREQUENCIES\ntext") == ((), (), None)
    valid = "VIBRATIONAL FREQUENCIES\n0: 1.0 cm**-1\nNORMAL MODES"
    tokens, spans, scale = _parse_stdout_frequencies(valid)
    assert tokens == ("1.0",) and len(spans) == 1 and scale is None
    with pytest.raises(ValueError, match="duplicated"):
        _parse_stdout_frequencies("VIBRATIONAL FREQUENCIES\n0: 1.0 cm**-1\n0: 2.0 cm**-1\n")
    with pytest.raises(ValueError, match="incomplete"):
        _parse_stdout_frequencies("VIBRATIONAL FREQUENCIES\n1: 1.0 cm**-1\n")


def test_thermochemistry_missing_and_nonunique_blocks_are_reported() -> None:
    missing = _parse_thermochemistry(
        "THERMOCHEMISTRY AT 298.15K\nTemperature ... 298.15 K\nPoint Group: C1"
    )
    assert missing.temperature_K == pytest.approx(298.15)
    assert "pressure_atm" in missing.missing_reasons
    duplicate = _parse_thermochemistry(
        "THERMOCHEMISTRY AT 298K\nPoint Group: C1\nTHERMOCHEMISTRY AT 299K\nPoint Group: C1"
    )
    assert duplicate.missing_reasons == ("thermochemistry_block_not_unique",)


@pytest.mark.parametrize("token", ["nan", "inf", "-inf", "not-a-number"])
def test_numeric_tokens_must_be_finite_numbers(token: str) -> None:
    with pytest.raises(ValueError):
        _number(token)
